services:
  # Backend API Service
  - type: web
    name: kempo-backend
    runtime: node
    region: frankfurt
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: kempo-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://kempo-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: kempo-frontend
    runtime: static
    region: frankfurt
    buildCommand: cd front && npm install && npm run build
    staticPublishPath: ./front/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://kempo-backend.onrender.com

# Database
databases:
  - name: kempo-database
    databaseName: kempo_db
    user: kempo_user
    region: frankfurt
